#:schema node_modules/wrangler/config-schema.json
name = "octomailer"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Enable Workers Logs for observability
[observability]
enabled = true
head_sampling_rate = 1.0  # 100% sampling rate for development

